name: Build and push the Image in ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the latest code
      uses: actions/checkout@v4

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1  # Replace with your region

    - name: Get Git Commit SHA
      id: sha
      run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com

    - name: Build docker image
      run: docker build -t my-spring-boot-app:${{ env.SHA }} .
    
    - name: Tag Docker Image
      run: docker tag my-spring-boot-app:${{ env.SHA }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/myrepo:${{ env.SHA }}

    - name: Push Docker Image to ECR
      run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/myrepo:${{ env.SHA }}
